# Generated by Django 6.0 on 2025-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Görsel')),
                ('url', models.URLField(blank=True, verbose_name='Proje Linki')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Linki')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('skills', models.ManyToManyField(to='skills.skill', verbose_name='Kullanılan Teknolojiler')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
