# Generated by Django 6.0 on 2025-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yetenek Adı')),
                ('level', models.IntegerField(default=50, verbose_name='Seviye (0-100)')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('icon', models.ImageField(blank=True, upload_to='skills/', verbose_name='İkon')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
                'ordering': ['order', 'name'],
            },
        ),
    ]
